server:
  port: 8090
spring:
  application:
    name: web-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
zuul:
  routes:
    api-mall:
      path: /api-mall/**
      serviceId: mall-web
